Conform to python standards with some pylint-ing
WhiteboardLiveCoding/WhiteboardLiveCoding pull request #13
Opened 2017-10-15 14:57 UTC by PaulSonOfLars

2017-10-15 16:12 UTC, martinzlocha requested changes

2017-10-15 16:12 UTC, martinzlocha commented on WLC/image_processing/preprocessor.py
> +        for cntour in contours:
Typo: contours

2017-10-17 11:32 UTC, PaulSonOfLars commented on WLC/image_processing/preprocessor.py
> +        for cntour in contours:
was intentional, but sure

2017-10-17 11:37 UTC, martinzlocha approved these changes

2017-10-17 11:38 UTC, merged