Set up basic GUI for the application
WhiteboardLiveCoding/WhiteboardLiveCoding pull request #23
Opened 2017-10-20 12:35 UTC by SuNaden

Using tkinter, we are now able to pick an image and execute our glorious app with one simple button click!

2017-10-20 17:45 UTC, martinzlocha requested changes
The code does not run correctly:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\zloch\Desktop\WhiteboardLiveCoding\WLC\utils\gui.py", line 21, in <lambda>
    quit_button = Button(self.master, text="Execute", command=lambda: self.execute_code(self.picture))
  File "C:\Users\zloch\Desktop\WhiteboardLiveCoding\WLC\utils\gui.py", line 31, in execute_code
    self.display_output(value)
  File "C:\Users\zloch\Desktop\WhiteboardLiveCoding\WLC\utils\gui.py", line 45, in display_output
    text.insert(END, code)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 3266, in insert
    self.tk.call((self._w, 'insert', index, chars) + args)
_tkinter.TclError: wrong # args: should be ".!text2 insert index chars ?tagList chars tagList ...?"

2017-10-20 20:25 UTC, PaulSonOfLars commented
@martinzlocha Works fine for me.

2017-10-21 16:03 UTC, PaulSonOfLars requested changes

2017-10-21 16:03 UTC, PaulSonOfLars commented on WLC/__main__.py
> +from tkinter import *
Avoid * imports, we don't want to mangle the namespace

2017-10-21 16:03 UTC, PaulSonOfLars commented on WLC/utils/gui.py
> +from tkinter import *
`*` import, as before

2017-10-21 16:03 UTC, PaulSonOfLars commented on WLC/utils/gui.py
> +                                              filetypes=(("png files", "*.png"), ("jpg files", "*.jpg"), ("all files", "*.*")))
120 char limit is nice

2017-10-21 16:03 UTC, PaulSonOfLars commented on WLC/utils/gui.py
> +        filename = filedialog.askopenfilename(initialdir="../../"+os.path.dirname(os.path.realpath(__file__)),
this isn't OS agnostic.
I don't believe `realpath` is needed here.
Use `dirname` to get parent directories instead of "`../`"

2017-10-21 16:03 UTC, PaulSonOfLars commented on WLC/image_processing/camera.py
> +            raise Exception("No image path specified")
Would be nice if we had a no-gui option for when we just want to test

2017-10-23 13:41 UTC, martinzlocha approved these changes

2017-10-23 13:49 UTC, PaulSonOfLars approved these changes

2017-10-24 09:48 UTC, merged